### ISSUE TITLE
Project does not build due to container conflict

### ISSUE THREAD

**Issue by simonl65** [nSoft-team/glassbox-nodejs-starter#4]
# Issue
Running `docker-compose up` fails with the following error:
```
ERROR: for postgres  Cannot create container for service postgres: Conflict. The container name "/postgres" is already in use by container "a3cbb7061663f05452b4f299e0f66b1baaf1a0b42d1f4a6fe902ff286d1593d3". You have to remove (or rename) that container to be able to reuse that name.
```

# Analysis
We already have a container named "postgres" for another project.

# Expected bahaviour
All containers should start without error.

# System details
OS: Windows 10 Pro
Version: 10.0.19044 Build 19044
Node: 16.17.0
Docker version: 20.10.17, build 100c701

**Comment by simonl65** [comment]
FIX: `container_name: postgres-starter-project` in docker-compose.yml

**Comment by VladislavTsygankov** [comment]
Just created a PR with fix. Please wait until for Nadav create merge
